[package]
name = "daily-scale"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
once_cell = "1.20.2"
rand = "0.8.5"
strum = "0.26.3"
strum_macros = "0.26.4"
